apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/biswa2015/argocd-assignment.git
    targetRevision: HEAD
    path: /app-of-apps # Path to the directory containing child app manifests
  destination:
    server: https://kubernetes.default.svc # Main ArgoCD server
    namespace: default