apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/biswa2015/argocd-assignment.git
    targetRevision: HEAD
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: main-cluster-namespace
  syncPolicy:
    automated:
      prune: true # Optional, if you want to remove resources not in Git
